"use client";

import Link from "next/link";
import type { PageAnalysis, ParsedPage } from "@/shared/types";
import { Shell } from "./shell";
import { Icon } from "./icons";
import { ErrorNotice, isActive, LoadingState, numberLabel } from "./ui";
import { HttpStatus, IssueCard } from "./audit-report";
import { useAudit } from "./use-audit";

export function PageInspector({ id, url }: { id: string; url: string }) {
  const { audit, loading, error, reload } = useAudit(id);
  const page = audit?.pages.find((item) => item.url === url || item.finalUrl === url);
  const issues = page ? audit?.issues.filter((issue) => issue.affectedUrls.includes(page.url) || issue.affectedUrls.includes(page.finalUrl)) ?? [] : [];
  return <Shell><Link className="back-link" href={`/audits/${encodeURIComponent(id)}`}><Icon name="arrow-left" size={16} /> Back to the report for {audit?.domain ?? "the website"}</Link>{loading && <LoadingState label="Loading page details…" />}{error && <ErrorNotice message={error} retry={() => { void reload(); }} />}{audit && !page && <div className="panel empty-state standalone"><Icon name="file" size={36} /><h1>{isActive(audit.status) ? "This page is not available yet." : "This URL is not part of the audit."}</h1><p className="break-url">{url || "No URL was specified."}</p><Link href={`/audits/${encodeURIComponent(id)}`} className="button secondary">Back to the report</Link></div>}{page && <>
    <div className="page-detail-heading"><div className="eyebrow">PAGE INSPECTOR</div><h1>{page.parsed?.title || "Page details"}</h1><a className="inspector-url" href={page.url} target="_blank" rel="noopener noreferrer">{page.url}<Icon name="external" size={16} /></a></div>
    <div className="inspector-summary"><span><HttpStatus code={page.statusCode} error={Boolean(page.error)} /> HTTP status</span><span className={page.indexable === true ? "success-text" : ""}><Icon name={page.indexable === true ? "check" : "shield"} size={16} /> {page.indexable === null ? "Indexability unknown" : page.indexable ? "Indexable based on observed signals" : "Non-indexable based on observed signals"}</span><span><Icon name="clock" size={16} /> {numberLabel(page.responseTimeMs)} ms</span><span><Icon name="layers" size={16} /> {issues.length} issue types</span></div>
    {page.error && <div className="notice warning-notice"><Icon name="alert" /><p>{page.error}</p></div>}
    {page.blockedByRobots && <div className="notice warning-notice"><Icon name="shield" /><p>Crawling this URL was blocked by robots.txt. Its content was not fetched.</p></div>}
    <div className="inspector-columns"><div className="inspector-main"><section className="panel detail-panel"><h2><Icon name="file" size={20} /> Metadata and indexability</h2><dl className="data-list metadata-list"><Data label="Title" value={page.parsed?.title} empty="No title observed" /><Data label="Meta description" value={page.parsed?.description} empty="No description observed" /><Data label="Resolved canonical" value={page.parsed?.canonical} empty="No valid canonical observed" /><Data label="Original canonical" value={page.parsed?.canonicalRaw} /><Data label="Effective directives (Googlebot)" value={page.parsed?.robots.join(" · ")} empty="No applicable directives observed" /><Data label="Declared language" value={page.parsed?.language} />{page.parsed && <><Data label="Noindex (Googlebot)" value={page.parsed.noindex ? "Yes" : "No"} /><Data label="Nofollow (Googlebot)" value={page.parsed.nofollow ? "Yes" : "No"} /><Data label="Canonical count" value={String(page.parsed.canonicalCount)} /><Data label="Invalid canonical" value={page.parsed.canonicalInvalid ? "Yes" : "No"} /></>}</dl>{page.parsed && <RobotDirectives parsed={page.parsed} />}{!page.parsed && <p className="detail-footnote">No HTML was analyzed for this page. Unavailable fields are not treated as missing tags.</p>}</section>
    {page.parsed && <><ContentDetails parsed={page.parsed} /><LinkDetails parsed={page.parsed} /><ImageDetails parsed={page.parsed} /><StructuredDetails parsed={page.parsed} /><SocialDetails parsed={page.parsed} /><section className="panel detail-panel"><h2><Icon name="search" size={20} /> Observed tracking</h2>{page.parsed.tracking.length > 0 ? <div className="detected-tags">{page.parsed.tracking.map((tool) => <span key={tool}><Icon name="check" size={14} /> {tool}</span>)}</div> : <p className="muted">No recognized tracking tools were detected in the received HTML.</p>}<p className="detail-footnote">Detection uses approximate HTML signals and does not confirm script execution.</p></section></>}
    <section className="page-issues"><div className="section-heading"><div><h2>Issues on this page <span className="count-badge">{issues.length}</span></h2><p>Explanations, fixes, and evidence for this URL.</p></div></div>{issues.length > 0 ? <div className="issue-list">{issues.map((issue) => <IssueCard key={issue.id} issue={issue} auditId={id} />)}</div> : <div className="panel empty-table">{audit && isActive(audit.status) ? "Issues will be finalized when the audit finishes." : "No issues were recorded for this URL."}</div>}</section>
    </div><aside className="inspector-side"><HttpDetails page={page} /><section className="panel detail-panel"><h2><Icon name="globe" size={20} /> Discovery</h2><dl className="data-list"><Data label="Depth from start" value={page.depth === null ? "No path inferred" : String(page.depth)} /><Data label="Present in sitemap" value={page.inSitemap ? "Yes" : "No"} /><Data label="Blocked by robots.txt" value={page.blockedByRobots ? "Yes" : "No"} /></dl><h4>Discovered from</h4>{page.discoveredFrom.length > 0 ? <ul className="plain-url-list">{page.discoveredFrom.map((source) => <li key={source}>{source}</li>)}</ul> : <p className="muted small-text">No source recorded.</p>}<p className="detail-footnote">Depth and links depend on the pages included in the crawl sample.</p></section></aside></div>
  </>}</Shell>;
}

function Data({ label, value, empty = "Unavailable" }: { label: string; value: string | null | undefined; empty?: string }) {
  return <div><dt>{label}</dt><dd className={`break-url ${!value ? "muted" : ""}`}>{value || empty}</dd></div>;
}

function RobotDirectives({ parsed }: { parsed: ParsedPage }) {
  return <><p className="detail-footnote">The effective policy combines generic and Googlebot directives. Crawl permissions for this tool are evaluated separately in robots.txt as SiteInspectorBot.</p>{parsed.robotDirectives && parsed.robotDirectives.length > 0 && <details className="data-details"><summary>Observed directives by agent and source</summary><div className="table-scroll capped-table" style={{ marginTop: 12 }}><table className="detail-table"><thead><tr><th>Source</th><th>Agent</th><th>Directives</th></tr></thead><tbody>{parsed.robotDirectives.map((entry, index) => <tr key={index}><td>{entry.source === "header" ? "X-Robots-Tag (HTTP)" : "Meta robots (HTML)"}</td><td>{entry.agent === "*" || entry.agent === "robots" ? "All agents" : entry.agent}</td><td className="break-url">{entry.directives.join(" · ") || "No value"}</td></tr>)}</tbody></table></div></details>}</>;
}

function HttpDetails({ page }: { page: PageAnalysis }) {
  return <section className="panel detail-panel"><h2><Icon name="terminal" size={20} /> HTTP response</h2><dl className="data-list"><div><dt>Final status</dt><dd><HttpStatus code={page.statusCode} error={Boolean(page.error)} /></dd></div><Data label="Final URL" value={page.finalUrl} /><Data label="Content-Type" value={page.contentType} /><Data label="Response time" value={`${numberLabel(page.responseTimeMs)} ms`} /><Data label="Request date" value={new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "medium" }).format(new Date(page.fetchedAt))} /></dl><h4>Redirects <span className="count-badge">{page.redirects.length}</span></h4>{page.redirects.length > 0 ? <ol className="redirect-chain">{page.redirects.map((hop, index) => <li key={index}><HttpStatus code={hop.statusCode} /><span>{hop.url}</span><Icon name="arrow" size={16} /><span className="muted">{hop.location}</span></li>)}</ol> : <p className="muted small-text">No redirects observed.</p>}</section>;
}

function ContentDetails({ parsed }: { parsed: ParsedPage }) {
  return <section className="panel detail-panel"><h2><Icon name="layers" size={20} /> Content and headings</h2><div className="content-stats"><div><strong>{numberLabel(parsed.wordCount)}</strong><span>Estimated words</span></div><div><strong>{parsed.h1.length}</strong><span>Headings H1</span></div><div><strong>{parsed.headings.length}</strong><span>Total headings</span></div></div><h4>Heading hierarchy</h4>{parsed.headings.length > 0 ? <div className="heading-tree">{parsed.headings.map((heading, index) => <div key={index} style={{ paddingLeft: `${(heading.level - 1) * 14}px` }}><span>H{heading.level}</span><p className={!heading.text ? "muted" : ""}>{heading.text || "Empty heading"}</p></div>)}</div> : <p className="muted">No headings observed.</p>}<details className="data-details"><summary>Extracted content sample</summary><p className="content-sample">{parsed.contentSample || "No text extracted."}</p><p className="detail-footnote">This evidence sample may not include all visible text.</p></details><details className="data-details"><summary>Content fingerprint</summary><code className="break-url content-hash">{parsed.contentHash || "Unavailable"}</code></details></section>;
}

function LinkDetails({ parsed }: { parsed: ParsedPage }) {
  const internal = parsed.links.filter((link) => link.internal).length;
  return <section className="panel detail-panel"><h2><Icon name="link" size={20} /> Observed links <span className="count-badge">{parsed.links.length}</span></h2><div className="detail-inline-stats"><span><strong>{internal}</strong> internal</span><span><strong>{parsed.links.length - internal}</strong> external</span><span><strong>{parsed.links.filter((link) => link.nofollow).length}</strong> nofollow</span></div><div className="table-scroll capped-table"><table className="detail-table"><thead><tr><th>Target URL</th><th>Text</th><th>Type</th><th>Nofollow</th></tr></thead><tbody>{parsed.links.map((link, index) => <tr key={index}><td className="break-url">{link.url}</td><td>{link.text || <span className="muted">No text</span>}</td><td>{link.internal ? "Internal" : "External"}</td><td>{link.nofollow ? "Yes" : "No"}</td></tr>)}</tbody></table>{parsed.links.length === 0 && <div className="empty-table">No links observed.</div>}</div><p className="detail-footnote">Broken links are inferred from internal URLs requested during the crawl. External targets are not checked.</p></section>;
}

function ImageDetails({ parsed }: { parsed: ParsedPage }) {
  return <section className="panel detail-panel"><h2><Icon name="file" size={20} /> Images <span className="count-badge">{parsed.images.length}</span></h2><div className="table-scroll capped-table"><table className="detail-table"><thead><tr><th>Resource</th><th>Alt</th><th>Declared size</th></tr></thead><tbody>{parsed.images.map((image, index) => <tr key={index}><td className="break-url">{image.src}{image.checkError && <small className="image-check-error">{image.checkError}</small>}</td><td>{image.alt === null ? <span className="missing-value">Missing alt attribute</span> : image.alt === "" ? <span className="muted">Empty alt</span> : image.alt}</td><td>{image.contentLength === null ? <span className="muted">Unavailable</span> : `${numberLabel(Math.round(image.contentLength / 1024))} KB`}</td></tr>)}</tbody></table>{parsed.images.length === 0 && <div className="empty-table">No images observed.</div>}</div><p className="detail-footnote">Size uses Content-Length when the server provides it and the resource is within the image check limit.</p></section>;
}

function StructuredDetails({ parsed }: { parsed: ParsedPage }) {
  return <section className="panel detail-panel"><h2><Icon name="terminal" size={20} /> Structured Data</h2><div className="detail-inline-stats"><span><strong>{parsed.jsonLdCount}</strong> JSON-LD blocks</span><span><strong>{parsed.schemaTypes.length}</strong> schema types</span></div>{parsed.schemaTypes.length > 0 ? <div className="detected-tags">{parsed.schemaTypes.map((type) => <span key={type}>{type}</span>)}</div> : <p className="muted">No schema types observed in JSON-LD.</p>}{parsed.jsonLdErrors.length > 0 && <><h4>JSON-LD errors</h4><ul className="warning-list">{parsed.jsonLdErrors.map((message, index) => <li key={index}>{message}</li>)}</ul></>}{parsed.schemaWarnings.length > 0 && <><h4>Basic observations</h4><ul className="warning-list">{parsed.schemaWarnings.map((message, index) => <li key={index}>{message}</li>)}</ul></>}<p className="detail-footnote">Basic syntax and consistency checks. This is not full Schema.org validation.</p></section>;
}

function SocialDetails({ parsed }: { parsed: ParsedPage }) {
  return <section className="panel detail-panel"><h2><Icon name="globe" size={20} /> Social metadata</h2><div className="social-columns"><div><h4>Open Graph</h4>{Object.keys(parsed.social.openGraph).length > 0 ? <dl className="data-list">{Object.entries(parsed.social.openGraph).map(([key, value]) => <Data key={key} label={key} value={value} empty="Empty value" />)}</dl> : <p className="muted">No Open Graph tags observed.</p>}</div><div><h4>Twitter Card</h4>{Object.keys(parsed.social.twitter).length > 0 ? <dl className="data-list">{Object.entries(parsed.social.twitter).map(([key, value]) => <Data key={key} label={key} value={value} empty="Empty value" />)}</dl> : <p className="muted">No Twitter Card tags observed.</p>}</div></div></section>;
}
