import type { Category, Severity } from "../shared/types";

interface IssueDefinition { name: string; category: Category; severity: Severity; description: string; whyItMatters: string; recommendation: string }
function rule(name: string, category: Category, severity: Severity, description: string, whyItMatters: string, recommendation: string): IssueDefinition {
  return { name, category, severity, description, whyItMatters, recommendation };
}

/** Stable keys are persisted in SQLite. Add a new key to introduce a new rule. */
export const issueCatalog = {
  http_4xx: rule("Pages returning 4xx errors", "HTTP", "high", "The observed HTTP response indicates that the page is unavailable.", "Visitors and search engines cannot access the expected content.", "Restore the content or fix the links. Redirect only when a relevant replacement exists."),
  http_5xx: rule("Pages returning 5xx errors", "HTTP", "critical", "The server returned an error when the page was requested.", "Server errors can prevent crawling and access to the site.", "Check server logs and availability, then repeat the audit after fixing the problem."),
  fetch_error: rule("Pages that could not be verified", "HTTP", "medium", "The request failed or the response body could not be retrieved within the limits.", "A timeout, network error, or security block prevents evaluation. It does not prove that the page is broken.", "Review the evidence and connectivity, then repeat the request with appropriate limits."),
  http_redirect: rule("Redirecting URLs", "HTTP", "info", "At least one HTTP redirect was observed.", "Redirects may be intentional, but they add a request before reaching the content.", "Check that the destination is correct and link directly to the final URL where appropriate."),
  redirect_chain: rule("Redirect chains", "HTTP", "medium", "The URL requires more than one redirect to reach its destination.", "Each hop adds latency and complicates crawling.", "Redirect directly to the final destination and update internal links."),
  robots_blocked: rule("Pages blocked by robots.txt", "Indexability", "info", "The crawler respected a Disallow rule and did not download these pages.", "The crawl block prevents content analysis. robots.txt alone does not guarantee removal from search indexes.", "Confirm that the block is intentional and allow crawling of content you want to evaluate."),
  googlebot_robots_blocked: rule("Googlebot blocked by robots.txt", "Indexability", "high", "The robots.txt rules read for this origin prohibit Googlebot from crawling these URLs.", "Googlebot cannot read the content or its directives. The URL may still appear in search results, so this does not confirm removal from the index.", "Allow crawling if Google should access the content. To exclude it from the index, consider an accessible noindex directive."),
  noindex: rule("Pages with noindex for Googlebot", "Indexability", "info", "A generic or Googlebot-specific noindex directive was detected in robots metadata or X-Robots-Tag.", "This directive asks Google to exclude the page if it can crawl it. It does not confirm the current indexing state.", "Keep it for content that should not be indexed; remove it if the page should appear in search results."),
  nofollow: rule("Pages with nofollow for Googlebot", "Indexability", "info", "A generic or Googlebot-specific page-level nofollow directive was detected.", "The directive may affect how Google interprets links on the page.", "Review whether it is needed or should be applied only to specific links."),
  canonical_missing: rule("Missing canonical", "Indexability", "low", "No canonical tag was found.", "An explicit canonical helps identify the preferred URL among equivalent variants.", "Add an absolute canonical pointing to the preferred URL where appropriate."),
  canonical_other: rule("Canonical points to another URL", "Indexability", "info", "The page declares a different URL as its canonical.", "This may intentionally consolidate signals in another document.", "Confirm that the destination is the equivalent version you want indexed."),
  canonical_invalid: rule("Invalid or ambiguous canonical", "Indexability", "high", "The canonical is empty, invalid, or declared more than once.", "Search engines may ignore invalid or ambiguous signals.", "Keep one canonical tag with a valid HTTP or HTTPS URL."),
  canonical_suspicious: rule("Potentially incorrect canonical", "Indexability", "high", "The canonical points outside the site or to an observed destination with an indexing restriction or error.", "An incorrect destination may consolidate signals in an unavailable or unrelated page.", "Check content equivalence and point to an accessible, indexable URL. A cross-domain canonical may be intentional."),
  title_missing: rule("Missing title", "Metadata", "high", "The page has no title element containing text.", "The title helps search engines and visitors understand the page.", "Add a unique, descriptive title that accurately represents the content."),
  title_short: rule("Very short title", "Metadata", "low", "The title contains fewer than 15 characters.", "A very brief title may not describe the content sufficiently. This threshold is a heuristic.", "Add useful context if needed without repeating unnecessary words."),
  title_long: rule("Very long title", "Metadata", "low", "The title exceeds 60 characters.", "It may be truncated in search results. Character counts are approximate guidance.", "Prioritize the main topic and shorten the title if it becomes unclear."),
  title_duplicate: rule("Duplicate titles", "Metadata", "medium", "Several pages share the same title after whitespace and case normalization.", "Unique titles help distinguish the purpose of each page.", "Differentiate titles for distinct content and consolidate equivalent URL variants where appropriate."),
  description_missing: rule("Missing meta description", "Metadata", "medium", "No meta description containing text was found.", "A useful description can help present the page in search results.", "Write a unique description summarizing the content and its value."),
  description_short: rule("Very short meta description", "Metadata", "low", "The description contains fewer than 70 characters.", "It may leave useful context unexplained. This threshold is a guideline.", "Describe the content more specifically if the current text is insufficient."),
  description_long: rule("Very long meta description", "Metadata", "low", "The description exceeds 160 characters.", "It may be truncated. Actual presentation depends on the search engine and device.", "Put the main information first and remove redundant text."),
  description_duplicate: rule("Duplicate meta descriptions", "Metadata", "low", "Several pages share the same normalized meta description.", "Repeated text does little to distinguish pages in search results.", "Write specific descriptions for distinct content."),
  social_incomplete: rule("Incomplete Open Graph metadata", "Metadata", "low", "At least one of og:title, og:description, and og:image is missing.", "These tags help control previews when links are shared.", "Add or complete all three fields with representative page content."),
  twitter_missing: rule("Missing Twitter Card", "Metadata", "info", "No twitter:card containing a value was found.", "Previews on platforms using Twitter Cards may be less predictable.", "Add twitter:card and review the sharing image and text if relevant to the site."),
  h1_missing: rule("Missing H1", "Content", "medium", "The page has no H1 containing text.", "A clear primary heading helps people understand the content structure.", "Add a descriptive H1 introducing the main topic."),
  h1_multiple: rule("Multiple H1 headings", "Content", "low", "Several H1 elements were found.", "This is not necessarily an error, but it may make the primary heading less clear.", "Review the structure and use secondary heading levels where appropriate."),
  heading_empty: rule("Empty headings", "Content", "low", "Headings without text were found.", "An empty heading contributes no semantic structure.", "Add text or replace the element if it is used only for visual styling."),
  heading_hierarchy: rule("Skipped heading levels", "Content", "low", "A heading skips more than one level or the first heading starts below H1.", "A consistent hierarchy makes content easier to navigate and understand.", "Review H1–H6 levels so they reflect sections and subsections."),
  thin_content: rule("Very little content", "Content", "low", "Fewer than 100 words were estimated in the main HTML content.", "This may indicate limited content or a page requiring JavaScript. Word count does not measure quality.", "Confirm the purpose of the page and whether the HTML contains the necessary information."),
  content_duplicate: rule("Potentially duplicate content", "Content", "medium", "Several pages have the same normalized main-text hash and at least 50 words.", "This may indicate equivalent variants or repeated content. Scripts and common navigation elements are excluded.", "Compare the pages and differentiate their content or consolidate equivalent URLs."),
  internal_link_broken: rule("Internal links to HTTP errors", "Links", "high", "An internal link points to a URL with an observed 4xx or 5xx response.", "Visitors and crawlers reach a page returning an error.", "Fix the link, restore the destination, or link to a valid alternative."),
  internal_link_unverified: rule("Internal destinations that could not be verified", "Links", "medium", "The destination request failed or its response could not be fully verified.", "A network, size-limit, or security failure does not prove that the link is broken.", "Review the technical error and repeat verification before modifying the link."),
  internal_link_redirect: rule("Internal links to redirects", "Links", "low", "Links point to URLs that redirected during this audit.", "Linking to the final destination avoids additional requests.", "Update internal links to the correct final URL."),
  deep_page: rule("Pages at high navigation depth", "Links", "low", "More than three navigation hops were needed from the starting page.", "High depth may make relevant content harder to discover. Only the observed graph is measured.", "Add links from related pages closer to the start when the content is important."),
  orphan_candidate: rule("Possible orphan pages", "Links", "info", "Sitemap URLs received no links from the observed HTML pages.", "These are candidates, not confirmed orphans. Crawl limits and HTML without JavaScript can hide links.", "Verify the full navigation and add internal links if the pages should be accessible."),
  image_alt_missing: rule("Images without an alt attribute", "Images", "medium", "Images missing the alt attribute were found.", "Alternative text describes informative images to screen readers and search engines.", "Add descriptive alt text to informative images. Use empty alt text for purely decorative images."),
  image_alt_empty: rule("Images with empty alt text", "Images", "info", "Images with empty alt text were found.", "This may be correct for decorative images. Visual review is needed to determine that.", "Confirm that the images are decorative and describe those that convey information."),
  image_heavy: rule("Potentially large images", "Images", "medium", "A measured Content-Length exceeds 500 KiB.", "Size may increase transfer cost. Visual loading and browser performance are not measured.", "Review dimensions, compression, and suitable formats. Confirm the actual transferred size."),
  schema_missing: rule("Pages without JSON-LD", "Structured Data", "info", "No application/ld+json blocks were found.", "JSON-LD can describe entities and enable search features, but not every page needs it.", "Add relevant structured data where appropriate. Microdata and RDFa are not evaluated."),
  schema_invalid: rule("Invalid JSON-LD", "Structured Data", "high", "A JSON-LD block could not be parsed as JSON.", "Consumers may ignore structured data with syntax errors.", "Fix the JSON syntax and validate the document again."),
  schema_inconsistent: rule("Possible JSON-LD inconsistencies", "Structured Data", "medium", "Basic checks found suspicious types, context, URLs, or identifiers.", "These signals need review. They are not a complete validation against Schema.org.", "Address the specific evidence and verify the markup with a dedicated structured-data validator."),
  tracking_detected: rule("Detected tracking tools", "Tracking", "info", "Recognizable analytics-tool patterns were found in the received HTML.", "This lists apparent integrations. It does not prove execution or assess consent or compliance.", "Compare the list with the integrations you expect to have installed."),
  sitemap_missing: rule("Sitemap not found", "Sitemap", "medium", "No usable sitemap was found at the checked locations.", "A sitemap helps communicate URLs that should be discovered.", "Publish a valid sitemap and declare its URL in robots.txt."),
  sitemap_error: rule("Sitemap reading errors", "Sitemap", "medium", "At least one sitemap document could not be requested or parsed.", "Sitemap coverage and comparisons may be incomplete.", "Review the observed error, XML structure, and document accessibility."),
  sitemap_http_error: rule("Sitemap URLs returning HTTP errors", "Sitemap", "high", "A URL listed in the sitemap returned a 4xx or 5xx error during the crawl.", "The sitemap should list available content.", "Fix the URL or remove it from the sitemap if it should no longer exist."),
  sitemap_noindex: rule("Sitemap URLs with noindex", "Sitemap", "high", "A sitemap URL declares noindex in its HTML or an applicable header.", "The sitemap and noindex express conflicting indexing intentions.", "Remove the URL from the sitemap or correct noindex according to the intended behavior."),
  sitemap_redirect: rule("Redirecting sitemap URLs", "Sitemap", "medium", "A sitemap URL produced an observed redirect.", "The sitemap should point directly to preferred final URLs.", "Replace redirecting URLs with their valid final destinations."),
  sitemap_absent_page: rule("Discovered pages missing from the sitemap", "Sitemap", "low", "Pages estimated to be indexable were found through navigation but not among the sitemap URLs read.", "This may be intentional because sitemaps do not need to be exhaustive. It may also indicate incomplete generation.", "Review whether these pages should be included. Comparisons are limited to the sitemaps that were read."),
  sitemap_unlinked: rule("Sitemap URLs without observed links", "Sitemap", "info", "No internal navigation link to these sitemap URLs was observed.", "The crawl sample does not confirm that they are orphans. Pages outside the limit or JavaScript-rendered links may be missing.", "Review the full internal navigation and link to these pages where necessary."),
} satisfies Record<string, IssueDefinition>;

export type IssueId = keyof typeof issueCatalog;
