import type { Category, Severity } from "../shared/types";

interface Reference { label: string; url: string }
interface IssueDefinition {
  name: string; category: Category; severity: Severity; description: string; whyItMatters: string; recommendation: string;
  kind: "issue" | "observation"; references: Reference[];
}
const google = (path: string) => `https://developers.google.com/search/docs/${path}`;
const canonicalReferences = [{ label: "Google: canonical URLs", url: google("crawling-indexing/consolidate-duplicate-urls") }];
const titleReferences = [{ label: "Google: descriptive title links", url: google("appearance/title-link") }];
const descriptionReferences = [{ label: "Google: snippets and meta descriptions", url: google("appearance/snippet") }];
const robotsReferences = [{ label: "Google: robots.txt limitations", url: google("crawling-indexing/robots/intro") }];
const directiveReferences = [{ label: "Google: robots meta and X-Robots-Tag", url: google("crawling-indexing/robots-meta-tag") }];
const socialReferences = [{ label: "Open Graph: required and optional sharing metadata", url: "https://ogp.me/" }];
const platformMetadataReferences = [{ label: "Google: supported metadata and other clients", url: google("crawling-indexing/special-tags") }];
const categoryReferences: Record<Category, Reference[]> = {
  HTTP: [{ label: "Google: HTTP status codes and crawling", url: "https://developers.google.com/crawling/docs/troubleshooting/http-status-codes" }],
  Indexability: canonicalReferences,
  Metadata: [...titleReferences, ...descriptionReferences],
  Content: [
    { label: "Google: SEO basics, content length and headings", url: google("fundamentals/seo-starter-guide") },
    { label: "WAI: heading structure", url: "https://www.w3.org/WAI/tutorials/page-structure/headings/" },
  ],
  Links: [{ label: "Google: crawlable links and internal navigation", url: google("crawling-indexing/links-crawlable") }],
  Images: [
    { label: "Google: image descriptions and optimization", url: google("appearance/google-images") },
    { label: "WAI: image alternative decision tree", url: "https://www.w3.org/WAI/tutorials/images/decision-tree/" },
  ],
  "Structured Data": [
    { label: "Google: supported structured-data formats", url: google("appearance/structured-data/intro-structured-data") },
    { label: "W3C: JSON-LD syntax and node objects", url: "https://www.w3.org/TR/json-ld11/" },
  ],
  Sitemap: [
    { label: "Google: when a sitemap is useful", url: google("crawling-indexing/sitemaps/overview") },
    { label: "Google: sitemap URL best practices", url: google("crawling-indexing/sitemaps/build-sitemap") },
  ],
  Tracking: [{ label: "Google: tags and verifying execution", url: "https://developers.google.com/tag-platform/gtagjs" }],
};
const observationIds = new Set([
  "fetch_error", "http_redirect", "redirect_chain", "robots_blocked", "googlebot_robots_blocked", "noindex", "nofollow",
  "canonical_missing", "canonical_other", "title_short", "title_long", "description_missing", "description_short", "description_long",
  "description_duplicate", "social_incomplete", "twitter_missing", "h1_missing", "h1_multiple", "heading_empty", "heading_hierarchy",
  "thin_content", "content_duplicate", "internal_link_unverified", "internal_link_redirect", "deep_page", "orphan_candidate",
  "image_alt_empty", "image_heavy", "schema_missing", "schema_inconsistent", "tracking_detected", "sitemap_missing", "sitemap_error",
  "sitemap_absent_page", "sitemap_unlinked",
]);
const referenceOverrides: Record<string, Reference[]> = {
  robots_blocked: robotsReferences, googlebot_robots_blocked: robotsReferences, noindex: directiveReferences, nofollow: directiveReferences,
  title_missing: titleReferences, title_short: titleReferences, title_long: titleReferences, title_duplicate: titleReferences,
  description_missing: descriptionReferences, description_short: descriptionReferences, description_long: descriptionReferences,
  description_duplicate: descriptionReferences, social_incomplete: socialReferences, twitter_missing: platformMetadataReferences,
  orphan_candidate: categoryReferences.Sitemap,
  http_redirect: [{ label: "Google: intentional redirects", url: google("crawling-indexing/301-redirects") }],
  redirect_chain: [{ label: "Google: redirects and redirect chains", url: google("crawling-indexing/301-redirects") }],
};
function rule(id: string, name: string, category: Category, severity: Severity, description: string, whyItMatters: string, recommendation: string): IssueDefinition {
  const kind = observationIds.has(id) ? "observation" : "issue";
  return { name, category, severity: kind === "observation" ? "info" : severity, description, whyItMatters, recommendation,
    kind, references: [...(referenceOverrides[id] ?? categoryReferences[category])] };
}

/** Stable keys are persisted in SQLite. Add a new key to introduce a new rule. */
export const issueCatalog = {
  http_4xx: rule("http_4xx", "Pages returning 4xx errors", "HTTP", "high", "The observed HTTP response indicates that the page is unavailable.", "Visitors and search engines cannot access the expected content.", "Restore the content or fix the links. Redirect only when a relevant replacement exists."),
  http_5xx: rule("http_5xx", "Pages returning 5xx errors", "HTTP", "high", "The requested URL returned a server error during this audit.", "This response prevents access to that URL. One observed error does not establish a site-wide outage.", "Check server logs and repeat the request to determine whether the failure is persistent."),
  fetch_error: rule("fetch_error", "Pages that could not be verified", "HTTP", "medium", "The request failed or the response body could not be retrieved within the limits.", "A timeout, network error, or security block prevents evaluation. It does not prove that the page is broken.", "Review the evidence and connectivity, then repeat the request with appropriate limits."),
  http_redirect: rule("http_redirect", "Redirecting URLs", "HTTP", "info", "At least one HTTP redirect was observed.", "Redirects may be intentional, but they add a request before reaching the content.", "Check that the destination is correct and link directly to the final URL where appropriate."),
  redirect_chain: rule("redirect_chain", "Redirect chains", "HTTP", "medium", "The URL requires more than one redirect to reach its destination.", "Each hop adds latency and complicates crawling.", "Redirect directly to the final destination and update internal links."),
  robots_blocked: rule("robots_blocked", "Pages blocked by robots.txt", "Indexability", "info", "The crawler respected a Disallow rule and did not download these pages.", "The crawl block prevents content analysis. robots.txt alone does not guarantee removal from search indexes.", "Confirm that the block is intentional and allow crawling of content you want to evaluate."),
  googlebot_robots_blocked: rule("googlebot_robots_blocked", "Googlebot blocked by robots.txt", "Indexability", "high", "The robots.txt rules read for this origin prohibit Googlebot from crawling these URLs.", "Googlebot cannot read the content or its directives. The URL may still appear in search results, so this does not confirm removal from the index.", "Allow crawling if Google should access the content. To exclude it from the index, consider an accessible noindex directive."),
  noindex: rule("noindex", "Pages with noindex for Googlebot", "Indexability", "info", "A generic or Googlebot-specific noindex directive was detected in robots metadata or X-Robots-Tag.", "This directive asks Google to exclude the page if it can crawl it. It does not confirm the current indexing state.", "Keep it for content that should not be indexed; remove it if the page should appear in search results."),
  nofollow: rule("nofollow", "Pages with nofollow for Googlebot", "Indexability", "info", "A generic or Googlebot-specific page-level nofollow directive was detected.", "The directive may affect how Google interprets links on the page.", "Review whether it is needed or should be applied only to specific links."),
  canonical_missing: rule("canonical_missing", "No explicit canonical observed", "Indexability", "info", "No canonical declaration was found in the received HTML head or HTTP Link header.", "Google can select a canonical without an explicit declaration. Absence alone is not an indexing error.", "Declare a preferred URL if equivalent variants need consolidation; otherwise review the observed URLs without assuming a defect."),
  canonical_other: rule("canonical_other", "Canonical points to another URL", "Indexability", "info", "The page declares a different URL as its canonical.", "This may intentionally consolidate signals in another document.", "Confirm that the destination is the equivalent version you want indexed."),
  canonical_invalid: rule("canonical_invalid", "Invalid or conflicting canonical declarations", "Indexability", "high", "A canonical declaration has no valid HTTP/HTTPS destination, or declarations resolve to different destinations.", "Invalid or contradictory canonical signals may be ignored. Identical repeated destinations are not treated as conflicting.", "Fix invalid destinations and make HTML and HTTP header declarations agree on the intended preferred URL."),
  canonical_suspicious: rule("canonical_suspicious", "Canonical destination has an observed restriction or HTTP error", "Indexability", "high", "The declared destination returned an observed 4xx/5xx response or declares noindex for Googlebot.", "The destination conflicts with the intent to select accessible, indexable content. Its actual indexing state is unknown.", "Review content equivalence and correct the observed HTTP error, noindex directive or canonical destination according to your intent."),
  title_missing: rule("title_missing", "Missing title in received HTML", "Metadata", "high", "The successful HTML response has no title element containing text.", "A descriptive title helps users and search engines identify the page. JavaScript was not rendered; this does not prove the rendered title or search result is empty.", "Provide a descriptive title and verify any JavaScript-generated title before treating this markup omission as resolved."),
  title_short: rule("title_short", "Title length flagged by an earlier heuristic", "Metadata", "info", "An earlier audit flagged a title shorter than 15 characters. Current audits do not generate this observation.", "Google has no minimum character requirement. Length alone does not establish whether a title is descriptive.", "Review relevance and clarity rather than expanding the title to meet a character target."),
  title_long: rule("title_long", "Title length flagged by an earlier heuristic", "Metadata", "info", "An earlier audit flagged a title longer than 60 characters. Current audits do not generate this observation.", "Google sets no title length limit; displayed title links may be truncated to fit device width.", "Review relevance, clarity and unnecessary repetition rather than a fixed character maximum."),
  title_duplicate: rule("title_duplicate", "Duplicate titles", "Metadata", "medium", "Several pages share the same title after whitespace and case normalization.", "Unique titles help distinguish the purpose of each page.", "Differentiate titles for distinct content and consolidate equivalent URL variants where appropriate."),
  description_missing: rule("description_missing", "Meta description opportunity", "Metadata", "info", "No non-empty meta description was found in the received HTML.", "Google primarily creates snippets from page content and may use a meta description when helpful. Absence does not prevent indexing.", "Consider a specific summary for important pages if it would communicate their purpose more clearly."),
  description_short: rule("description_short", "Description length flagged by an earlier heuristic", "Metadata", "info", "An earlier audit flagged fewer than 70 characters. Current audits do not generate this observation.", "Google has no minimum description length. Relevance and specificity matter more than character count.", "Review whether the description accurately summarizes this page without targeting a minimum length."),
  description_long: rule("description_long", "Description length flagged by an earlier heuristic", "Metadata", "info", "An earlier audit flagged more than 160 characters. Current audits do not generate this observation.", "Google sets no meta-description length limit; snippets may be truncated to fit the device.", "Put useful information first and remove redundant text if needed; no fixed maximum is required."),
  description_duplicate: rule("description_duplicate", "Duplicate meta descriptions", "Metadata", "low", "Several pages share the same normalized meta description.", "Repeated text does little to distinguish pages in search results.", "Write specific descriptions for distinct content."),
  social_incomplete: rule("social_incomplete", "Optional Open Graph sharing metadata", "Metadata", "info", "One or more Open Graph basic fields are absent: og:title, og:type, og:image or og:url. og:description is optional.", "These fields describe shared-link previews. Absence alone does not establish a Google Search defect.", "If social sharing matters for this site, provide the four basic fields and optionally a useful description."),
  twitter_missing: rule("twitter_missing", "Optional Twitter Card metadata", "Metadata", "info", "No non-empty twitter:card field was found in the received HTML. Sharing previews were not tested.", "This is platform-specific metadata. Its absence alone does not establish a Google Search defect.", "If a platform-specific sharing preview matters, review that platform's current requirements and verify the actual preview before changing metadata."),
  h1_missing: rule("h1_missing", "No H1 element in received HTML", "Content", "info", "The successful HTML response contains no H1 element. JavaScript was not rendered.", "A clear main heading can help users understand a page, but Google has no requirement for exactly one H1 or an ideal heading count.", "Review the visible main heading and semantic structure in context before changing markup."),
  h1_multiple: rule("h1_multiple", "Multiple H1 elements in received HTML", "Content", "info", "More than one H1 element was found; visual prominence was not evaluated.", "Multiple H1 elements do not establish an SEO defect. The main visual title should be clear to users.", "Review the page's main title and section structure; do not change headings solely to reach a count of one."),
  heading_empty: rule("heading_empty", "Headings without text in received HTML", "Content", "info", "A heading has no text content in the successful HTML response. JavaScript and accessible names were not evaluated.", "A heading may be populated by JavaScript or named through accessibility attributes. Static HTML alone does not establish a rendered empty heading.", "Inspect the rendered heading and its accessible name; add meaningful content only if it is actually missing."),
  heading_hierarchy: rule("heading_hierarchy", "Heading levels to review", "Content", "info", "The HTML document order includes a downward level skip or starts below H1; separate page regions were not evaluated.", "A logical structure helps navigation and accessibility. Heading order is not a Google ranking requirement, and separate page regions can have their own structure.", "Review headings in the context of sections and landmarks rather than treating every document-order skip as an error."),
  thin_content: rule("thin_content", "Word count flagged by an earlier heuristic", "Content", "info", "An earlier audit flagged fewer than 100 estimated words. Current audits do not generate this observation.", "Google has no magical minimum or maximum word count. HTML extraction without JavaScript does not measure content quality.", "Review whether the page satisfies its intended purpose without adding text to meet a word target."),
  content_duplicate: rule("content_duplicate", "Matching extracted HTML text", "Content", "info", "Several pages share the same normalized, non-empty main-text hash. JavaScript was not rendered.", "This can identify equivalent URL variants, but does not establish identical rendered content or a duplicate-content penalty.", "Compare the documents and intended URLs before differentiating content or consolidating variants."),
  internal_link_broken: rule("internal_link_broken", "Internal links to HTTP errors", "Links", "high", "An internal link points to a URL with an observed 4xx or 5xx response.", "Visitors and crawlers reach a page returning an error.", "Fix the link, restore the destination, or link to a valid alternative."),
  internal_link_unverified: rule("internal_link_unverified", "Internal destinations that could not be verified", "Links", "medium", "The destination request failed or its response could not be fully verified.", "A network, size-limit, or security failure does not prove that the link is broken.", "Review the technical error and repeat verification before modifying the link."),
  internal_link_redirect: rule("internal_link_redirect", "Internal links to redirects", "Links", "low", "Links point to URLs that redirected during this audit.", "Linking to the final destination avoids additional requests.", "Update internal links to the correct final URL."),
  deep_page: rule("deep_page", "Pages at high navigation depth", "Links", "low", "More than three navigation hops were needed from the starting page.", "High depth may make relevant content harder to discover. Only the observed graph is measured.", "Add links from related pages closer to the start when the content is important."),
  orphan_candidate: rule("orphan_candidate", "Possible orphan pages", "Links", "info", "Sitemap URLs received no links from the observed HTML pages.", "These are candidates, not confirmed orphans. Crawl limits and HTML without JavaScript can hide links.", "Verify the full navigation and add internal links if the pages should be accessible."),
  image_alt_missing: rule("image_alt_missing", "Images without an alt attribute", "Images", "medium", "Images missing the alt attribute were found.", "Alternative text describes informative images to screen readers and search engines.", "Add descriptive alt text to informative images. Use empty alt text for purely decorative images."),
  image_alt_empty: rule("image_alt_empty", "Images with empty alt text", "Images", "info", "An image has an empty alt attribute in the received HTML.", "Empty alt can be correct for decorative or redundant images. Visual purpose was not evaluated.", "Keep empty alt when appropriate; describe information or functionality that is otherwise unavailable."),
  image_heavy: rule("image_heavy", "Image Content-Length to review", "Images", "info", "A successful HEAD response reports Content-Length above the application's 500 KiB heuristic.", "This is a declared resource size, not measured browser transfer or loading impact. Google sets no universal 500 KiB image cutoff.", "Review the image's purpose, dimensions, compression and responsive variants if transfer cost matters; verify actual browser loading before concluding there is a performance problem."),
  schema_missing: rule("schema_missing", "No JSON-LD observed", "Structured Data", "info", "No application/ld+json blocks were found in the received HTML; Microdata, RDFa and JavaScript-injected markup were not evaluated.", "Structured data is optional for general indexing and can support eligible search features. Google also accepts Microdata and RDFa.", "Consider relevant structured data only when it describes the actual content and a useful supported search feature."),
  schema_invalid: rule("schema_invalid", "Malformed JSON in a JSON-LD block", "Structured Data", "medium", "A received application/ld+json block has a JSON syntax error.", "Consumers cannot reliably parse this block. This affects the markup, not proof of general indexing failure or ranking loss.", "Fix the reported JSON syntax error and validate relevant structured data against its intended search feature."),
  schema_inconsistent: rule("schema_inconsistent", "JSON-LD checks from an earlier heuristic", "Structured Data", "info", "An earlier audit reported semantic heuristics. Current audits validate JSON syntax and inventory types only.", "Repeated identifiers can merge properties; contexts and explicit types are not universally required. These older checks do not establish invalid JSON-LD.", "Use a standards-aware or relevant rich-result validator before modifying these constructs."),
  tracking_detected: rule("tracking_detected", "Detected tracking tools", "Tracking", "info", "Recognizable analytics-tool patterns were found in the received HTML.", "This lists apparent integrations. It does not prove execution or assess consent or compliance.", "Compare the list with the integrations you expect to have installed."),
  sitemap_missing: rule("sitemap_missing", "No sitemap found at checked locations", "Sitemap", "info", "This audit did not find a usable sitemap at the locations it checked; a sitemap may exist elsewhere.", "A sitemap can help discovery, but a small, well-linked site may not need one. This does not establish an indexing defect.", "Consider a sitemap when it would help discovery or communicate preferred URLs; publish and declare it if useful for this site."),
  sitemap_error: rule("sitemap_error", "Sitemap reading errors", "Sitemap", "medium", "At least one sitemap document could not be requested or parsed.", "Sitemap coverage and comparisons may be incomplete.", "Review the observed error, XML structure, and document accessibility."),
  sitemap_http_error: rule("sitemap_http_error", "Sitemap URLs returning HTTP errors", "Sitemap", "high", "A URL listed in the sitemap returned a 4xx or 5xx error during the crawl.", "The sitemap should list available content.", "Fix the URL or remove it from the sitemap if it should no longer exist."),
  sitemap_noindex: rule("sitemap_noindex", "Sitemap URLs with noindex", "Sitemap", "high", "A sitemap URL declares noindex in its HTML or an applicable header.", "The sitemap and noindex express conflicting indexing intentions.", "Remove the URL from the sitemap or correct noindex according to the intended behavior."),
  sitemap_redirect: rule("sitemap_redirect", "Redirecting sitemap URLs", "Sitemap", "medium", "A sitemap URL produced an observed redirect.", "The sitemap should point directly to preferred final URLs.", "Replace redirecting URLs with their valid final destinations."),
  sitemap_absent_page: rule("sitemap_absent_page", "Discovered pages missing from the sitemap", "Sitemap", "low", "Pages estimated to be indexable were found through navigation but not among the sitemap URLs read.", "This may be intentional because sitemaps do not need to be exhaustive. It may also indicate incomplete generation.", "Review whether these pages should be included. Comparisons are limited to the sitemaps that were read."),
  sitemap_unlinked: rule("sitemap_unlinked", "Sitemap URLs without observed links", "Sitemap", "info", "No internal navigation link to these sitemap URLs was observed.", "The crawl sample does not confirm that they are orphans. Pages outside the limit or JavaScript-rendered links may be missing.", "Review the full internal navigation and link to these pages where necessary."),
} satisfies Record<string, IssueDefinition>;

export type IssueId = keyof typeof issueCatalog;
